=== AnartzPagaldai/Reto-colaborativo-Grupo01/LMSG/clasificacion/clasificacion.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clasificacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="equipo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="victorias" type="xs:integer"/>
              <xs:element name="goles_a_favor" type="xs:integer"/>
              <xs:element name="goles_en_contra" type="xs:integer"/>
              <xs:element name="diferencia_de_goles" type="xs:integer"/>
            </xs:sequence>
            <xs:attribute name="posicion" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="split" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AnartzPagaldai/Reto-colaborativo-Grupo01/LMSG/clasificacion/clasificacionGenerada.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clasificacion SYSTEM "clasificacion.dtd">
<clasificacion split="1" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
               xs:noNamespaceSchemaLocation="clasificacion.xsd">
    <fecha>25/05/23</fecha>
    <equipo posicion="1">
        <nombre>El Barrio</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="2">
        <nombre>Rayo de Barcelona</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="3">
        <nombre>Saiyans FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="4">
        <nombre>1K FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="5">
        <nombre>Ultimate Mostoles</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="6">
        <nombre>Aniquiladores FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="7">
        <nombre>Porcinos FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="8">
        <nombre>Kunisports</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="9">
        <nombre>Jijantes FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="10">
        <nombre>Los Troncos FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="11">
        <nombre>PIO FC</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
    <equipo posicion="12">
        <nombre>xBuyer Team</nombre>
        <victorias>0</victorias>
        <goles_a_favor>0</goles_a_favor>
        <goles_en_contra>0</goles_en_contra>
        <diferencia_de_goles>0</diferencia_de_goles>
    </equipo>
</clasificacion>
