=== AnartzPagaldai/Reto-colaborativo-Grupo01/LMSG/jornadas/jornadas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="jornadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jornada" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tipo_split" type="xs:string"/>
              <xs:element name="tipo_jornada" type="xs:string"/>
              <xs:element name="partido" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="equipo1" type="xs:string"/>
                    <xs:element name="goles_equipo1" type="xs:integer"/>
                    <xs:element name="equipo2" type="xs:string"/>
                    <xs:element name="goles_equipo2" type="xs:integer"/>
                    <xs:element name="fecha_partido" type="xs:string"/>
                    <xs:element name="lugar_partido" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id_partido" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="num_jornada" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== AnartzPagaldai/Reto-colaborativo-Grupo01/LMSG/Jornadas/jornadas.xml
<?xml version="1.0" encoding="UTF-8"?>
<jornadas xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation = "jornadas.xsd">
<jornada num_jornada="1" id_jornada="1">
  <tipo_split> VERANO</tipo_split>
  <tipo_jornada> NORMAL</tipo_jornada>
  <partido id_partido="1">
    <equipo1> JIJANTES FC</equipo1>
    <goles_equipo1> 3</goles_equipo1>
    <equipo2>PORCINOS FC</equipo2>
    <goles_equipo2>5</goles_equipo2>
    <fecha_partido> 05/10/2023</fecha_partido>
    <lugar_partido> CUPRA ARENA</lugar_partido>
  </partido>
  <partido id_partido="2">
    <equipo1> RAYO DE BARCELONA</equipo1>
    <goles_equipo1> 1</goles_equipo1>
    <equipo2>ULTIMATE MOSTOLES</equipo2>
    <goles_equipo2>0</goles_equipo2>
    <fecha_partido> 05/10/2023</fecha_partido>
    <lugar_partido> CUPRA ARENA</lugar_partido>
  </partido>
  
  
  <partido id_partido="3">
    <equipo1> PIO FC</equipo1>
    <goles_equipo1> 1</goles_equipo1>
    <equipo2>LOS TRONCOS FC</equipo2>
    <goles_equipo2>2</goles_equipo2>
    <fecha_partido> 05/10/2023</fecha_partido>
    <lugar_partido> CUPRA ARENA</lugar_partido>
  </partido>
  
  
</jornada>
</jornadas>
