=== AnartzPagaldai/Reto-colaborativo-Grupo01/P/Kings League/src/Modelo/XML/jornadas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="jornadas" type="tipo_jornadas"/>
    <xs:complexType name="tipo_jornadas">
      <xs:sequence>
          <xs:element name="jornada" maxOccurs="13" type="tipo_jornada"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="tipo_jornada">
      <xs:sequence>
        <xs:element name="tipo_split" type="xs:string"/>
        <xs:element name="tipo_jornada" type="xs:string"/>
        <xs:element name="partido" type="tipo_partido" maxOccurs="6"/>
      </xs:sequence>
      <xs:attribute name="num_jornada" type="xs:int" use="required"/>
      <xs:attribute name="id_jornada" type="xs:int" use="required"/>
      </xs:complexType>
      
      <xs:complexType name="tipo_partido">
      <xs:sequence>
        <xs:element name="equipo1" type="xs:string"/>
        <xs:element name="goles_equipo1" type="xs:int" minOccurs="0"/>
        <xs:element name="equipo2" type="xs:string"/>
        <xs:element name="goles_equipo2" type="xs:int" minOccurs="0"/>
        <xs:element name="fecha_partido" type="xs:string"/>
        <xs:element name="lugar_partido" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id_partido" type="xs:int" use="required"/>
      </xs:complexType>
      
</xs:schema>

=== AnartzPagaldai/Reto-colaborativo-Grupo01/P/Kings League/src/Modelo/XML/ultimaJornada.xml
<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE jornadas SYSTEM "jornadas.dtd">
            <jornadas xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation = "jornadas.xsd"><jornada num_jornada="13" id_jornada="13">
                    <tipo_split>INVIERNO</tipo_split>
                    <tipo_jornada>PLAY-OFF</tipo_jornada><partido id_partido="71">
            <equipo1>xBuyer Team</equipo1>
            <goles_equipo1>0</goles_equipo1>
            <equipo2>1K FC</equipo2>
            <goles_equipo2>6</goles_equipo2>
            <fecha_partido>30/05/23</fecha_partido>
            <lugar_partido>Cupra Arena</lugar_partido>
            </partido><partido id_partido="72">
            <equipo1>Kunisports</equipo1>
            <goles_equipo1>0</goles_equipo1>
            <equipo2>PIO FC</equipo2>
            <goles_equipo2>8</goles_equipo2>
            <fecha_partido>30/05/23</fecha_partido>
            <lugar_partido>Cupra Arena</lugar_partido>
            </partido><partido id_partido="73">
            <equipo1>1K FC</equipo1>
            <goles_equipo1>58</goles_equipo1>
            <equipo2>PIO FC</equipo2>
            <goles_equipo2>9</goles_equipo2>
            <fecha_partido>30/05/23</fecha_partido>
            <lugar_partido>Cupra Arena</lugar_partido>
            </partido></jornada></jornadas>
